name: CI
on: [push]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1
    
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      
      - name:  Build
        run: npm run build
        
      - name: Deploy to IIS
        run: Copy-Item C:\actions-runner\_work\CICD_Demo\CICD_Demo\dist\my-first-project/* C:/inetpub/wwwroot/dotnetcore-webapp -Recurse -Force
 
